# version: "3.7"

services:

  postgres:
    image: postgres:buster
    hostname: postgres
    container_name: webapp_template_postgres
    restart: always
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
